apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-practice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-python
  template:
    metadata:
      labels:
        app: flask-python
    spec:
      containers:
        - name: deploy-container
          image: poojadevops1012/python-flask-rest-api-pro:flask-api
          ports:
            - containerPort: 80
