apiVersion: v1
kind: Service
metadata:
  name: flask-python-service
  labels:
    app: flask-python
spec:
  type: LoadBalancer
  selector:
    app: flask-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

